name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.2', '8.3', '8.4' ]
        laravel: [ '10.*', '11.*' ]
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none
        extensions: mbstring, intl
    - run: composer install --no-interaction --prefer-dist
    - run: XDEBUG_MODE=off ./vendor/bin/phpunit --testdox --colors=always
    - run: vendor/bin/phpstan analyse --no-progress