name: Packagist Update

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
    - name: Notify Packagist
      run: |
        curl -s -X POST \
          -H 'Content-Type: application/json' \
          -d '{"repository":{"url":"https://github.com/${{ github.repository }}"}}' \
          "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}"

